// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class ActorList
{
    public int ActorId { get; set; }

    public string ActorName { get; set; }

    public string ActorImgPath { get; set; }

    public string ActorDescription { get; set; }
}