// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class BlackList
{
    public int BlacklistId { get; set; }

    public int MemberId { get; set; }

    public int BlockedMemberId { get; set; }

    public DateTime? CreationDate { get; set; }

    public string Reason { get; set; }
}