// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class ChatRoom
{
    public int ChatRoomId { get; set; }

    public int SenderId { get; set; }

    public DateTime SendTime { get; set; }

    public string ChatMessage { get; set; }

    public virtual MemberInfo Sender { get; set; }
}