// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class Cinema
{
    public int CinemaId { get; set; }

    public string CinemaName { get; set; }

    public string CinemaAddress { get; set; }

    public string CinemaPhone { get; set; }
}