// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class DirectorList
{
    public int DirectorId { get; set; }

    public string DirectorName { get; set; }

    public string DirectorImgPath { get; set; }

    public string DirectorDescription { get; set; }
}