// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class GiftList
{
    /// <summary>
    /// 贈品清單編號
    /// </summary>
    public int GiftListId { get; set; }

    /// <summary>
    /// 贈品編號
    /// </summary>
    public int GiftId { get; set; }
}