// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class Invite
{
    /// <summary>
    /// 流水號
    /// </summary>
    public int InvitelId { get; set; }

    /// <summary>
    /// 會員ID
    /// </summary>
    public int MemberId { get; set; }

    /// <summary>
    /// 受邀好友ID
    /// </summary>
    public int InvitedMemberId { get; set; }

    /// <summary>
    /// 邀請時間
    /// </summary>
    public DateTime InviteTime { get; set; }

    /// <summary>
    /// 邀請訊息
    /// </summary>
    public string InviteMsg { get; set; }

    /// <summary>
    /// 狀態代碼:
    /// Initial初始(I)
    /// Accept接受(A)
    /// Reject拒絕(R)
    /// Pedding忽略(P)
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 狀態時間
    /// </summary>
    public DateTime StatusTime { get; set; }
}