// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class MemberNotice
{
    /// <summary>
    /// 會員通知編號
    /// </summary>
    public int MemberNoticeId { get; set; }

    /// <summary>
    /// 會員編號
    /// </summary>
    public int MemberId { get; set; }

    /// <summary>
    /// 通知標題
    /// </summary>
    public string Title { get; set; }

    /// <summary>
    /// 通知內容
    /// </summary>
    public string NoticeContent { get; set; }

    /// <summary>
    /// 狀態:已讀,未讀
    /// </summary>
    public string Status { get; set; }

    /// <summary>
    /// 通知參照的單號
    /// </summary>
    public int? RefNo { get; set; }

    /// <summary>
    /// 通知時間
    /// </summary>
    public DateTime CreTime { get; set; }

    /// <summary>
    /// 建立通知的事件
    /// </summary>
    public string Action { get; set; }
}