// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class PlanList
{
    public int PlanId { get; set; }

    public string PlanName { get; set; }

    public virtual ICollection<ViedoPlanList> ViedoPlanLists { get; set; } = new List<ViedoPlanList>();
}