// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class PlayListItem
{
    public int PlayListItemId { get; set; }

    public int PlayListId { get; set; }

    public int VideoId { get; set; }

    public int VideoPosition { get; set; }

    public DateTime? VideoAddedAt { get; set; }
}