// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class PostUserReaction
{
    public int CountId { get; set; }

    public int ArticleId { get; set; }

    public int PostId { get; set; }

    public int MemberId { get; set; }

    public bool ReactionType { get; set; }
}