// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class ReservationDetail
{
    public int ReservationId { get; set; }

    public int? MemberId { get; set; }

    public int? ShowtimeId { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public string TypeOfTicket { get; set; }

    public decimal? Price { get; set; }

    public string Status { get; set; }

    public string PaymentMethod { get; set; }

    public int? CouponId { get; set; }

    public int? TicketCount { get; set; }

    public virtual MemberInfo Member { get; set; }

    public virtual ICollection<SessionSeat> SessionSeats { get; set; } = new List<SessionSeat>();

    public virtual Showtime Showtime { get; set; }
}