// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class SessionSeat
{
    public int SessionSeatId { get; set; }

    public int? SeatId { get; set; }

    public int? ShowtimeId { get; set; }

    public byte? SeatStatus { get; set; }

    public int? ReservationId { get; set; }

    public virtual ReservationDetail Reservation { get; set; }

    public virtual Seat Seat { get; set; }

    public virtual Showtime Showtime { get; set; }
}