// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class ShoppingCart
{
    public int ShoppingCartId { get; set; }

    public int? MemberId { get; set; }

    public int? PlanId { get; set; }

    public int? VideoId { get; set; }

    public virtual MemberInfo Member { get; set; }

    public virtual PlanList Plan { get; set; }

    public virtual VideoList Video { get; set; }
}