// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class Theme
{
    public int ThemeId { get; set; }

    public string ThemeName { get; set; }
}