// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VdbAPI.Models;

public partial class VideoList
{
    public int VideoId { get; set; }

    public int TypeId { get; set; }

    public string VideoName { get; set; }

    public int? SeriesId { get; set; }

    public int MainGenreId { get; set; }

    public int? SeasonId { get; set; }

    public int? Episode { get; set; }

    public TimeOnly? RunningTime { get; set; }

    public bool IsShowing { get; set; }

    public DateOnly? ReleaseDate { get; set; }

    public decimal? Rating { get; set; }

    public decimal? Popularity { get; set; }

    public string ThumbnailPath { get; set; }

    public string Lang { get; set; }

    public string Summary { get; set; }

    public int? Views { get; set; }

    public string AgeRating { get; set; }

    public string TrailerUrl { get; set; }

    public string Bgpath { get; set; }
}