// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backstage.Models;

public partial class CastList
{
    public int CastId { get; set; }

    public int? VideoId { get; set; }

    public int? ActorId { get; set; }

    public virtual ActorList Actor { get; set; }

    public virtual VideoList Video { get; set; }
}