// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backstage.Models;

public partial class Cinema
{
    public int CinemaId { get; set; }

    public string CinemaName { get; set; }

    public string CinemaAddress { get; set; }

    public string CinemaPhone { get; set; }

    public virtual ICollection<Hall> Halls { get; set; } = new List<Hall>();

    public virtual ICollection<NowShowingTheater> NowShowingTheaters { get; set; } = new List<NowShowingTheater>();
}