// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class DirectorForVideoList
{
    public int SerialId { get; set; }

    public int DirectorId { get; set; }

    public int VideoId { get; set; }

    public virtual DirectorList Director { get; set; }

    public virtual VideoList Video { get; set; }
}