// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class DirectorList
{
    public int DirectorId { get; set; }

    public string DirectorName { get; set; }

    public byte[] DirectorImage { get; set; }

    public virtual ICollection<DirectorForVideoList> DirectorForVideoLists { get; set; } = new List<DirectorForVideoList>();
}