// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class GenresForVideoList
{
    public int SerialId { get; set; }

    public int? VideoId { get; set; }

    public int? GenreId { get; set; }

    public virtual GenreList Genre { get; set; }

    public virtual VideoList Video { get; set; }
}