// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class Hall
{
    public int HallsId { get; set; }

    public int? CinemaId { get; set; }

    public string HallsName { get; set; }

    public int? SeatCapacity { get; set; }

    public virtual Cinema Cinema { get; set; }

    public virtual ICollection<Seat> Seats { get; set; } = new List<Seat>();

    public virtual ICollection<ShowingHall> ShowingHalls { get; set; } = new List<ShowingHall>();

    public virtual ICollection<Showtime> Showtimes { get; set; } = new List<Showtime>();
}