// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backstage.Models;

public partial class MemberPlayList
{
    public int MemberPlayListId { get; set; }

    public int MemberId { get; set; }

    public int PlayListId { get; set; }

    public DateTime AddedOtherMemberPlayListAt { get; set; }

    public virtual MemberInfo Member { get; set; }

    public virtual PlayList PlayList { get; set; }
}