// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class Order
{
    public int OrderId { get; set; }

    public int? ShoppingCartId { get; set; }

    public int? CouponId { get; set; }

    public DateOnly? OrderDate { get; set; }

    public decimal? OrderTotalPrice { get; set; }

    public string DeliveryName { get; set; }

    public string DeliveryAddress { get; set; }

    public int? PaymentStatus { get; set; }

    public int? DriverId { get; set; }

    public int? DeliveryStatus { get; set; }

    public DateTime? LastEditTime { get; set; }

    public virtual CouponInfo Coupon { get; set; }

    public virtual MemberInfo Driver { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual ShoppingCart ShoppingCart { get; set; }
}