// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class TheaterList
{
    public int TheaterId { get; set; }

    public string TheaterName { get; set; }
}