// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class VideoStreamingLinkList
{
    public int StreamingId { get; set; }

    public int PlatformId { get; set; }

    public string StreamLink { get; set; }

    public int? VideoId { get; set; }

    public virtual StreamingPlatformList Platform { get; set; }

    public virtual VideoList Video { get; set; }
}