// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backend.Models;

public partial class ViedoPlanList
{
    public int ViedoPlanId { get; set; }

    public int PlanId { get; set; }

    public int ViedoId { get; set; }

    public virtual PlanList Plan { get; set; }

    public virtual ICollection<ShoppingCart> ShoppingCarts { get; set; } = new List<ShoppingCart>();

    public virtual VideoList Viedo { get; set; }
}