// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backstage.Models;

public partial class FriendChat
{
    public int FriendChatId { get; set; }

    public int SenderId { get; set; }

    public int ReceiverId { get; set; }

    public DateTime? SendTime { get; set; }

    public string FriendChat1 { get; set; }

    public virtual MemberInfo Receiver { get; set; }

    public virtual MemberInfo Sender { get; set; }
}