// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace Backstage.Models;

public partial class GenreList
{
    public int GenreId { get; set; }

    [Display(Name ="類型名稱")]
    public string GenreName { get; set; }

    public virtual ICollection<GenresForVideoList> GenresForVideoLists { get; set; } = new List<GenresForVideoList>();
    [JsonIgnore]
    public virtual ICollection<VideoList> VideoLists { get; set; } = new List<VideoList>();
}