// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel;

namespace Backstage.Models;

public partial class Hall
{
    public int HallsId { get; set; }

   
    public int? CinemaId { get; set; }

    [DisplayName("影廳名稱")]
    public string HallsName { get; set; }

    [DisplayName("座位數量")]
    public int? SeatCapacity { get; set; }

    [DisplayName("影院名稱")]
    public virtual Cinema Cinema { get; set; }

    public virtual ICollection<Seat> Seats { get; set; } = new List<Seat>();

    public virtual ICollection<ShowingHall> ShowingHalls { get; set; } = new List<ShowingHall>();

    public virtual ICollection<Showtime> Showtimes { get; set; } = new List<Showtime>();
}