// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Backstage.Models;

public partial class ImageForVideoList
{
    public int Id { get; set; }
    [Display(Name = "圖片ID")]
    public int? ImageId { get; set; }

    [Display(Name = "影片名稱")]
    public int? VideoId { get; set; }

    public virtual ImageList Image { get; set; }

    public virtual VideoList Video { get; set; }
}