// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Backstage.Models;

public partial class ImageList
{
    public int ImageId { get; set; }
    [Display(Name="上傳檔案路徑")]
    public string ImagePath { get; set; }

    public virtual ICollection<ImageForVideoList> ImageForVideoLists { get; set; } = new List<ImageForVideoList>();
}