// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backstage.Models;

public partial class KeywordForVideoList
{
    public int SerialId { get; set; }

    public int? KeywordId { get; set; }

    public int? VideoId { get; set; }

    public virtual KeywordList Keyword { get; set; }

    public virtual VideoList Video { get; set; }
}