// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backstage.Models;

public partial class ProductList
{
    public int ProductId { get; set; }

    public string ProductName { get; set; }

    public decimal? ProductPrice { get; set; }

    public string ProductDescription { get; set; }

    public string ProductImg { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();
}