// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backstage.Models;

public partial class ReservationDetail
{
    public int ReservationId { get; set; }

    public int MemberId { get; set; }

    public DateTime? PurchaseDate { get; set; }

    public decimal? Total { get; set; }

    public string Status { get; set; }

    public int? PaymentMethod { get; set; }

    public int? CouponId { get; set; }

    public virtual MemberInfo Member { get; set; }
}