// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Backstage.Models;

public partial class SeriesList
{
    public int SeriesId { get; set; }
    [Display(Name ="系列名稱")]
    public string SeriesName { get; set; }

    public virtual ICollection<SeasonList> SeasonLists { get; set; } = new List<SeasonList>();

    public virtual ICollection<VideoList> VideoLists { get; set; } = new List<VideoList>();
}