// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backstage.Models;

public partial class Ticket
{
    public int TicketId { get; set; }

    public int ReservationId { get; set; }

    public int? TypeOfTicket { get; set; }

    public int? ShowtimeId { get; set; }

    public int? SeatId { get; set; }

    public decimal? Price { get; set; }

    public virtual Seat Seat { get; set; }

    public virtual Showtime Showtime { get; set; }

    public virtual TypeOfTicket TypeOfTicketNavigation { get; set; }
}