// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Backstage.Models;

public partial class VideoPlanVideoPlan
{
    public int VideoPlanId { get; set; }

    public int PlanId { get; set; }

    public int VideoId { get; set; }

    public string VideoName { get; set; }

    public string PlanName { get; set; }
}